
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.4.218:8080/eureka/
server:
  port: 8764
spring:
  application:
    name: credit-provider-service


jedis :  
  pool :  
    host : 127.0.0.1  
    port : 6379  
    config :  
      maxTotal: 100  
      maxIdle: 10  
      maxWaitMillis : 100000      
    